default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: original_product_db
test:
  <<: *default
  database: original_product_db_test

production:
  <<: *default
  database: original_product_db_production
